#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
~/.local/bin/yadm submodule update --recursive --init

# check if zsh is installed
if ! command -v zsh &> /dev/null 
then
    sudo apt update -y
    sudo apt upgrade
    sudo apt-get install zsh -y
    echo "zsh install done"
else
    echo "Zsh is installed"
fi

# check if python3 is installed
if ! command -v python3 &> /dev/null 
then
    sudo apt update -y
    sudo apt upgrade
    sudo apt-get install python3 -y
    echo "python install done"
else
    echo "Python3 is installed"
fi

# check if pyenv is installed
if ! command -v pyenv &> /dev/null 
then
    sudo curl https://pyenv.run | bash
    echo "pyenv install done"
else
    echo "pyenv is installed"
fi

# check if poetry is installed
if ! command -v poetry &> /dev/null 
then
    sudo curl -sSL https://install.python-poetry.org | python3 -
    echo "poetry install done"
else
    echo "poetry is installed"
fi

# check if starship is installed
if ! command -v starship &> /dev/null 
then
    sudo curl -sS https://starship.rs/install.sh | sh
    echo "starship install done"
else
    echo "starship is installed"
fi

# done
echo "Bootstrapping complete"
sudo chsh -s $(which zsh)
