#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
~/.local/bin/yadm submodule update --recursive --init

# check if zsh is installed
sudo apt update 
sudo apt upgrade -y
sudo apt-get install zsh -y
echo "zsh install done"

# install yadm
sudo apt-get install yadm -y
echo "yadm installed"

# check if python3 is installed
sudo apt-get install python3 -y
echo "python install done"

# check if pyenv is installed
sudo curl https://pyenv.run | bash
echo "pyenv install done"

# check if poetry is installed
sudo curl -sSL https://install.python-poetry.org | python3 -
echo "poetry install done"

# check if starship is installed
sudo curl -sS https://starship.rs/install.sh | sh
echo "starship install done"

#updating yadm url and config
echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:maxirass/.dotfile.git"
yadm config yadm.cipher openssl

# done
echo "Bootstrapping complete"
chsh -s $(which zsh)
