#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
~/.local/bin/yadm submodule update --recursive --init

# check if zsh is installed
sudo apt update 
sudo apt upgrade -y
sudo apt-get install zsh -y
echo "zsh install done"

# install yadm
sudo apt-get install yadm -y
echo "yadm installed"

# check if starship is installed
sudo curl -sS https://starship.rs/install.sh | sh
echo "starship install done"

# install TPM (Tmux Package Manager)
git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm

#updating yadm url and config
echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:maxirass/.dotfile.git"
yadm config yadm.cipher openssl

# done
echo "Bootstrapping complete"
chsh -s $(which zsh)
