# ~/.config/starship.toml

add_newline = false
command_timeout = 1000

format = """
$character\
$os$hostname\
$directory\
$git_branch\
$git_status \
$python\
$conda\
$memory_usage\
[](#1C3A5E)$time[ ](#1C3A5E)$cmd_duration
[└─>](bold green) """


continuation_prompt = '▶▶ '

[character]
success_symbol = "🚀 "
error_symbol = "🔥 "

[time]
disabled = false
time_format = "%T"
style = "bg:#1d2230"
format = '[[ 󱑍 $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'

[cmd_duration]
format = 'last command: [$duration](bold yellow)'

# ---

[os]
format = '[$symbol](bold white) '   
disabled = false

# Shows the hostname
[hostname]
ssh_only = false
format = 'on [$hostname](bold yellow) '
disabled = false
ssh_symbol = " "

# Shows current directory
[directory]
truncation_length = 3
fish_style_pwd_dir_length=2
home_symbol = '󰋜 ~'
read_only_style = '197'
read_only = '  '
format = 'at [$path]($style)[$read_only]($read_only_style) '

# Shows current git branch
[git_branch]
symbol = " "
format = 'via [$symbol$branch]($style)'
# truncation_length = 4
truncation_symbol = '…/'
style = 'bold green'

# Shows current git status
[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bold green'
conflicted = '🏳'
up_to_date = ''
untracked = ' '
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = ' '
modified = ' '
staged = '[++\($count\)](green)'
renamed = '襁 '
deleted = ' '


# ---
[conda]
symbol = '🅒'
style = 'bold green'
ignore_base = true
format = '[$symbol$environment]($style)'

[memory_usage]
symbol = "󰍛 "
disabled = true
style='bold dimmed white'
threshold = 1
format = "$symbol [${ram}(|${swap})]($style) "

[python]
symbol = " "
pyenv_version_name = true
detect_files = ['.python-version', '__init__.py', 'pyproject.toml']
